title: Intro Guide
author: Discovery Scholars
email: berkeley.discovery.scholars@gmail.com
description: 
  How to start learning data science using the Data Scholars Discovery Guide.

theme: jekyll-theme-slate
